http:
  routers:
    headscale:
      rule: Host(`n8n.165.22.241.196.nip.io`)
      # rule: Host(`n8n.grep2000.com`)
      service: n8n-vps
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

  services:
    n8n-svc:
      loadBalancer:
        servers: http://10.64.0.7:5678
